### NUMPY

In [1]:
import numpy as np

### 1D

In [2]:
a=np.array([10,20,30,50,5,60])

#### Attributes of arrays

#### ndim

#### Dtype

#### shape

#### size

In [3]:
a.dtype

dtype('int32')

In [4]:
a.shape

(6,)

In [5]:
a.ndim

1

In [6]:
a.size

6

In [7]:
a[0]

10

In [8]:
a[1]

20

### MULTIDIMENSIONAL ARRAY

In [9]:
a_4d=np.array([[[[1,2,3],[2,5,6],[2,3,0],[7,9,9],[2,9,0],[3,5,9]]]])

In [10]:
a.size

6

In [11]:
a

array([10, 20, 30, 50,  5, 60])

In [12]:
a_4d

array([[[[1, 2, 3],
         [2, 5, 6],
         [2, 3, 0],
         [7, 9, 9],
         [2, 9, 0],
         [3, 5, 9]]]])

In [13]:
a_4d.shape

(1, 1, 6, 3)

In [14]:
a_4d.size

18

In [15]:
a_4d.ndim

4

In [17]:
a_4d[1][1]

IndexError: index 1 is out of bounds for axis 0 with size 1

In [20]:
a_2d=np.array([[1,2,3,4,],[9,8,6,5],[7,3,2,3]])

In [21]:
a_2d[1][2]

6

In [22]:
a_2d[2][1]

3

In [23]:
a_1d=np.array([[1,2,3,4,],[9,8,6,5],[7,3,2,3]],dtype=float)

In [24]:
a_1d

array([[1., 2., 3., 4.],
       [9., 8., 6., 5.],
       [7., 3., 2., 3.]])

In [25]:
a_1d.shape

(3, 4)

In [26]:
a_1d.ndim

2

In [27]:
a_1d.size

12

In [36]:
a_3d=np.array([
    [
        [2,3,4],[3,4,5],[2,8,9]
    ],[
        [4,3,1],[3,7,8],[2,9,5]
    ],[
        [3,4,4],[3,1,9],[1,0,4]
    ]
],dtype=float)

In [37]:
a_3d.size

27

In [38]:
a_3d.shape

(3, 3, 3)

In [39]:
a_3d.ndim

3

In [40]:
a_3d[1][1][2]

8.0

In [41]:
a_3d

array([[[2., 3., 4.],
        [3., 4., 5.],
        [2., 8., 9.]],

       [[4., 3., 1.],
        [3., 7., 8.],
        [2., 9., 5.]],

       [[3., 4., 4.],
        [3., 1., 9.],
        [1., 0., 4.]]])

In [42]:
a_3d[1][0]

array([4., 3., 1.])

### NP FULL

In [45]:
a_full=np.full((3,5,2),7)

In [46]:
a_full

array([[[7, 7],
        [7, 7],
        [7, 7],
        [7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7],
        [7, 7],
        [7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7],
        [7, 7],
        [7, 7],
        [7, 7]]])

### ZEROES AND ONES

In [52]:
a_zeroes=np.zeros((2,3,4))

In [53]:
a_zeroes

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [54]:
a_zeroes.ndim

3

### EMPTY AND RANDOM

In [55]:
E=np.empty((3,3))

In [56]:
E

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [2.33646845e-307, 1.42413555e-306, 1.78019082e-306],
       [1.37959740e-306, 2.29178686e-312, 2.11392372e-307]])

In [57]:
E.ndim

2

In [58]:
E.size

9

In [59]:
E.shape

(3, 3)

### RANDOM

In [61]:
B=np.random.random((2,3))

In [62]:
B

array([[0.93271411, 0.41016674, 0.14261714],
       [0.77213512, 0.97394759, 0.97153564]])

In [64]:
B.size

6

In [65]:
B.shape

(2, 3)

In [66]:
B.ndim

2